import streamlit as st
import requests
import json

# Set page configuration
st.set_page_config(
    page_title="AI Exercise Routine Generator",
    page_icon="💪",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Title and description
st.title("💪 AI Exercise Routine Generator")
st.markdown("Get a personalized weekly exercise routine generated by AI based on your profile and goals!")

# Initialize session state
if 'routine_generated' not in st.session_state:
    st.session_state.routine_generated = False

def query_ollama(prompt, model="gemma3:270m"):
    """
    Query Ollama API with the given prompt
    """
    try:
        url = "http://localhost:11434/api/generate"
        data = {
            "model": model,
            "prompt": prompt,
            "stream": False
        }
        
        response = requests.post(url, json=data, timeout=120)
        response.raise_for_status()
        
        result = response.json()
        
        # Check for model-specific errors
        if 'error' in result:
            if 'system memory' in result['error']:
                return f"⚠️ Memory Error: The model '{model}' requires more RAM than available. Please try a smaller model like 'gemma2:2b' or 'gemma3:270m'."
            else:
                return f"Model Error: {result['error']}"
        
        return result.get('response', 'No response received')
        
    except requests.exceptions.ConnectionError:
        return "❌ Error: Cannot connect to Ollama. Please make sure Ollama is running.\n\nTo start Ollama:\n1. Open a terminal\n2. Run: ollama serve\n3. Keep it running while using this app"
    except requests.exceptions.Timeout:
        return "⏱️ Error: Request timed out. The model might be loading or the prompt is too complex. Please try again."
    except Exception as e:
        return f"❌ Error: {str(e)}"

def create_exercise_prompt(age, health_issues, exercise_time, goal):
    """
    Create a detailed prompt for the AI model
    """
    prompt = f"""
You are a certified fitness trainer and exercise physiologist. Create a detailed weekly exercise routine for a person with the following profile:

Age: {age} years old
Health Issues: {health_issues}
Available Exercise Time: {exercise_time} minutes per day
Primary Goal: {goal}

Please provide a comprehensive 7-day weekly exercise routine that includes:

1. Specific exercises for each day
2. Duration and intensity for each exercise
3. Rest periods between exercises
4. Safety considerations based on age and health issues
5. Progressive modifications for improvement
6. Warm-up and cool-down activities

Format the response as a structured weekly plan:
- Monday: [exercises and details]
- Tuesday: [exercises and details]
- Wednesday: [exercises and details]
- Thursday: [exercises and details]
- Friday: [exercises and details]
- Saturday: [exercises and details]
- Sunday: [exercises and details]

Make sure the routine is:
- Safe and appropriate for the person's age and health conditions
- Realistic given the available time constraint
- Effective for achieving the stated goal
- Progressive and sustainable

Please be specific about sets, reps, duration, and intensity levels.
    """
    return prompt

# Sidebar for user inputs
with st.sidebar:
    st.header("👤 Your Profile")
    
    # Age input
    age = st.slider(
        "Your Age (years)",
        min_value=16,
        max_value=80,
        value=30,
        help="Enter your current age in years"
    )
    
    # Health issues input
    health_issues = st.text_area(
        "Known Health Issues",
        placeholder="e.g., bad knees, back problems, heart condition, diabetes, etc.\nLeave empty if none.",
        help="List any health conditions, injuries, or physical limitations"
    )
    
    if not health_issues.strip():
        health_issues = "None reported"
    
    # Exercise time input
    exercise_time = st.selectbox(
        "Daily Exercise Time Available",
        options=[15, 30, 45, 60, 90, 120],
        index=2,  # Default to 45 minutes
        help="How many minutes per day can you dedicate to exercise?"
    )
    
    # Goal selection
    goal = st.radio(
        "Primary Goal",
        options=["Lose weight", "Gain muscle"],
        help="Select your main fitness objective"
    )
    
    # Model selection
    st.header("🤖 AI Model")
    model_options = [
        "gemma3:270m"  # Only working model with available system memory
    ]
    
    selected_model = st.selectbox(
        "Choose AI Model",
        options=model_options,
        index=0,
        help="Model optimized for your system's available memory"
    )

# Main content area
col1, col2 = st.columns([2, 1])

with col1:
    st.header("📋 Your Exercise Profile")
    
    # Display user profile summary
    st.info(f"""
    **Age:** {age} years  
    **Health Issues:** {health_issues}  
    **Daily Exercise Time:** {exercise_time} minutes  
    **Goal:** {goal}  
    **AI Model:** {selected_model}
    """)
    
    # Generate button
    if st.button("🚀 Generate My Exercise Routine", type="primary", use_container_width=True):
        with st.spinner("🤖 AI is creating your personalized exercise routine..."):
            prompt = create_exercise_prompt(age, health_issues, exercise_time, goal)
            routine = query_ollama(prompt, selected_model)
            
            st.session_state.routine = routine
            st.session_state.routine_generated = True
    
    # Display generated routine
    if st.session_state.routine_generated and 'routine' in st.session_state:
        st.header("🏋️ Your Personalized Weekly Exercise Routine")
        st.success("✅ Your custom exercise routine has been generated!")
        
        # Display the routine in an expandable section
        with st.expander("📅 View Complete Weekly Routine", expanded=True):
            if "Error:" in st.session_state.routine:
                st.error(st.session_state.routine)
            else:
                st.markdown(st.session_state.routine)
        
        # Download option
        st.download_button(
            label="📥 Download Routine as Text File",
            data=st.session_state.routine,
            file_name=f"exercise_routine_{age}y_{goal.lower().replace(' ', '_')}.txt",
            mime="text/plain"
        )

with col2:
    st.header("ℹ️ Tips & Information")
    
    st.markdown("""
    ### 🎯 Getting Started
    1. Fill in your profile information in the sidebar
    2. Select your primary fitness goal
    3. Choose how much time you can dedicate daily
    4. Click "Generate My Exercise Routine"
    
    ### 💡 Tips for Success
    - **Start gradually** - Don't jump into intense workouts immediately
    - **Listen to your body** - Rest when you need to
    - **Stay consistent** - Regular moderate exercise beats sporadic intense sessions
    - **Track progress** - Keep a log of your workouts
    
    ### ⚠️ Important Notes
    - Always consult with a healthcare provider before starting a new exercise program
    - If you have health conditions, get medical clearance first
    - Stop exercising if you feel pain or discomfort
    - Stay hydrated and maintain proper nutrition
    
    ### 🤖 About the AI
    This app uses advanced AI models running through Ollama to generate personalized exercise routines based on your specific needs and goals.
    """)
    
    # Status indicator
    st.markdown("### 🔌 System Status")
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("Check Ollama"):
            test_response = query_ollama("Hello", selected_model)
            if "Error:" in test_response or "❌" in test_response or "⚠️" in test_response:
                st.error("Connection failed")
                st.write(test_response)
            else:
                st.success("✅ Ollama connected")
    
    with col2:
        if st.button("List Models"):
            try:
                response = requests.get("http://localhost:11434/api/tags", timeout=5)
                if response.status_code == 200:
                    models = response.json().get('models', [])
                    st.success(f"✅ {len(models)} models available")
                    for model in models:
                        model_name = model.get('name', 'Unknown')
                        size_gb = model.get('size', 0) / (1024**3)
                        st.write(f"📦 {model_name} ({size_gb:.1f} GB)")
                else:
                    st.error("❌ Cannot fetch models")
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
    
    # Memory warning
    st.info("💡 **Tip**: If you get memory errors, try smaller models like 'gemma2:2b' or 'gemma3:270m'")
    
    # Quick model test
    st.markdown("### 🧪 Quick Model Test")
    if st.button("Test Selected Model"):
        with st.spinner(f"Testing {selected_model}..."):
            test_result = query_ollama("Say hello in one sentence.", selected_model)
            if "Error:" in test_result or "❌" in test_result or "⚠️" in test_result:
                st.error("❌ Model test failed")
                st.write(test_result)
            else:
                st.success("✅ Model working!")
                st.write(f"Response: {test_result}")

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center'>
        <p>💪 AI Exercise Routine Generator | Powered by Ollama & Streamlit</p>
        <p><small>⚠️ This is for informational purposes only. Always consult healthcare professionals before starting new exercise programs.</small></p>
    </div>
    """, 
    unsafe_allow_html=True
)