import streamlit as st
import requests
import json
import os

# Set page configuration
st.set_page_config(
    page_title="UAB Sveikata - AI Exercise Assistant",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Title and description
st.title("🏥 UAB Sveikata - AI Exercise Assistant")
st.markdown("**Professional health and exercise guidance powered by AI**")
st.markdown("Get a personalized weekly exercise routine generated by our AI health assistant!")

# Initialize session state
if 'routine_generated' not in st.session_state:
    st.session_state.routine_generated = False

def query_ollama(prompt, model="gemma3:270m"):
    """
    Query Ollama API with the given prompt
    """
    try:
        url = "http://localhost:11434/api/generate"
        data = {
            "model": model,
            "prompt": prompt,
            "stream": False
        }
        
        response = requests.post(url, json=data, timeout=120)
        response.raise_for_status()
        
        result = response.json()
        
        # Check for model-specific errors
        if 'error' in result:
            if 'system memory' in result['error']:
                return f"⚠️ Memory Error: The model '{model}' requires more RAM than available. Please try a smaller model like 'gemma2:2b' or 'gemma3:270m'."
            else:
                return f"Model Error: {result['error']}"
        
        return result.get('response', 'No response received')
        
    except requests.exceptions.ConnectionError:
        return "❌ Error: Cannot connect to Ollama. Please make sure Ollama is running.\n\nTo start Ollama:\n1. Open a terminal\n2. Run: ollama serve\n3. Keep it running while using this app"
    except requests.exceptions.Timeout:
        return "⏱️ Error: Request timed out. The model might be loading or the prompt is too complex. Please try again."
    except Exception as e:
        return f"❌ Error: {str(e)}"

def query_openrouter(prompt, model="google/gemma-2-9b-it"):
    """
    Query OpenRouter API with the given prompt
    """
    api_key = st.session_state.get('openrouter_api_key', '')
    
    if not api_key:
        return "❌ Error: OpenRouter API key is required. Please enter it in the sidebar."
    
    try:
        url = "https://openrouter.ai/api/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {api_key}",
            "HTTP-Referer": "http://localhost:8501",
            "X-Title": "Exercise Routine Generator",
            "Content-Type": "application/json"
        }
        
        data = {
            "model": model,
            "messages": [
                {"role": "user", "content": prompt}
            ]
        }
        
        response = requests.post(url, headers=headers, json=data, timeout=60)
        response.raise_for_status()
        
        result = response.json()
        
        if 'error' in result:
            return f"❌ OpenRouter Error: {result['error'].get('message', 'Unknown error')}"
        
        if 'choices' in result and len(result['choices']) > 0:
            return result['choices'][0]['message']['content']
        else:
            return "❌ No response received from OpenRouter"
        
    except requests.exceptions.RequestException as e:
        if hasattr(e, 'response') and hasattr(e.response, 'status_code') and e.response.status_code == 401:
            return "❌ Error: Invalid OpenRouter API key. Please check your API key."
        return f"❌ OpenRouter connection error: {str(e)}"
    except Exception as e:
        return f"❌ Error: {str(e)}"

def validate_health_response(response):
    """
    Validate that the response follows UAB Sveikata requirements (very flexible)
    """
    if not response or len(response.strip()) < 10:
        return False, "Response is too short or empty"
    
    # Clean the response for validation
    clean_response = response.strip()
    
    # Very flexible greeting check - just look for key elements
    has_uab_sveikata = 'UAB Sveikata' in clean_response
    has_assistant = 'assistant' in clean_response.lower() or 'health' in clean_response.lower()
    
    # Very flexible disclaimer check - look for any medical-related disclaimer
    medical_disclaimer_keywords = [
        'AI and does not constitute',
        'does not constitute medical advice',
        'medical advice',
        'professional medical',
        'generated by AI',
        'informational purposes'
    ]
    
    has_disclaimer = any(keyword.lower() in clean_response.lower() for keyword in medical_disclaimer_keywords)
    
    # Check if response seems to be about health/exercise (very flexible)
    health_keywords = ['exercise', 'workout', 'fitness', 'health', 'training', 'routine', 'physical', 'activity', 'muscle', 'weight', 'cardio', 'strength', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'plan', 'week']
    has_health_content = any(keyword.lower() in clean_response.lower() for keyword in health_keywords)
    
    # For very short responses, be even more lenient
    if len(clean_response) < 100:
        if has_uab_sveikata:
            return True, "Short response but contains UAB Sveikata branding"
    
    # Build validation message
    score = 0
    issues = []
    
    if has_uab_sveikata:
        score += 1
    else:
        issues.append("Missing UAB Sveikata branding")
        
    if has_disclaimer:
        score += 1
    else:
        issues.append("Missing medical disclaimer")
        
    if has_health_content:
        score += 1
    else:
        issues.append("Not clearly health/exercise related")
    
    # Accept if at least 2 out of 3 criteria are met
    if score >= 2:
        return True, "Response meets basic requirements"
    
    return False, f"Insufficient compliance (score {score}/3): {', '.join(issues)}"

def generate_routine(age, health_issues, exercise_time, goal, provider, model):
    """
    Generate exercise routine using selected provider and model with validation and post-processing
    """
    prompt = create_exercise_prompt(age, health_issues, exercise_time, goal)
    
    if provider == "Ollama":
        response = query_ollama(prompt, model)
    elif provider == "OpenRouter":
        response = query_openrouter(prompt, model)
    else:
        return "❌ Error: Invalid provider selected"
    
    # Check for API errors first
    if response.startswith("❌") or response.startswith("⚠️") or response.startswith("⏱️"):
        return response
    
    # Debug option - show validation bypass in sidebar
    skip_validation = st.sidebar.checkbox("🔧 Skip validation (Debug)", help="Skip response validation for testing")
    
    if skip_validation:
        return response
    
    # Post-process response to ensure UAB Sveikata compliance
    processed_response = post_process_response(response, age, health_issues, exercise_time, goal)
    
    # Validate the processed response
    is_valid, validation_message = validate_health_response(processed_response)
    
    if not is_valid:
        # Show debug info in expander
        with st.expander("🔍 Debug Info - Validation Details"):
            st.write("**Validation Error:**", validation_message)
            st.write("**Original Response:**")
            st.code(response)
            st.write("**Processed Response:**")
            st.code(processed_response[:300] + "..." if len(processed_response) > 300 else processed_response)
        
        return f"⚠️ Response validation failed: {validation_message}\n\nCheck debug info above."
    
    return processed_response

def post_process_response(response, age, health_issues, exercise_time, goal):
    """
    Post-process AI response to ensure UAB Sveikata compliance
    """
    # Clean the response
    clean_response = response.strip()
    
    # Required greeting
    required_greeting = 'Hello, I am the "UAB Sveikata" health assistant.'
    
    # Required disclaimer  
    required_disclaimer = 'This answer is generated by AI and does not constitute professional medical advice.'
    
    # Check if greeting exists (flexible)
    has_uab_greeting = any(phrase in clean_response for phrase in [
        'UAB Sveikata', 'health assistant', 'Hello, I am'
    ])
    
    # Check if disclaimer exists (flexible)
    has_disclaimer = any(phrase.lower() in clean_response.lower() for phrase in [
        'medical advice', 'AI and does not constitute', 'professional medical'
    ])
    
    # Build the final response
    final_response = ""
    
    # Add greeting if missing or incorrect
    if not has_uab_greeting or not clean_response.startswith('Hello, I am the "UAB Sveikata"'):
        final_response += required_greeting + "\n\n"
    
    # Add the main content
    main_content = clean_response
    
    # Remove any existing incomplete greetings/disclaimers
    if main_content.startswith('Okay, I understand.'):
        main_content = main_content.replace('Okay, I understand.', '').strip()
    
    # If the response doesn't contain exercise content, generate minimal content
    if not any(day in main_content.lower() for day in ['monday', 'tuesday', 'exercise', 'workout', 'routine']):
        main_content = f"""Based on your profile (Age: {age}, Goal: {goal}, Time: {exercise_time} min/day), here's a weekly exercise routine:

Monday: Cardio warm-up (10 min) + Strength training (30 min) + Cool-down (5 min)
Tuesday: Moderate cardio workout ({exercise_time} min)
Wednesday: Strength training + flexibility exercises
Thursday: Active recovery or light cardio
Friday: Full-body workout routine
Saturday: Outdoor activity or sport of choice
Sunday: Rest day with light stretching

Safety notes: Start gradually, listen to your body, and stay hydrated."""
    
    final_response += main_content
    
    # Add disclaimer if missing
    if not has_disclaimer:
        if not final_response.endswith('.'):
            final_response += "."
        final_response += f"\n\n{required_disclaimer}"
    
    return final_response

def create_exercise_prompt(age, health_issues, exercise_time, goal):
    """
    Create a detailed prompt for the AI model with UAB Sveikata requirements
    """
    # Simplified prompt for smaller models like gemma3:270m
    prompt = f"""Hello, I am the "UAB Sveikata" health assistant.

Create a weekly exercise plan:
- Age: {age} years
- Health: {health_issues} 
- Time: {exercise_time} minutes/day
- Goal: {goal}

Monday: [exercises]
Tuesday: [exercises] 
Wednesday: [exercises]
Thursday: [exercises]
Friday: [exercises]
Saturday: [exercises]
Sunday: [exercises]

This answer is generated by AI and does not constitute professional medical advice.
    """
    return prompt

# Sidebar for user inputs
with st.sidebar:
    st.header("👤 Your Profile")
    
    # Age input
    age = st.slider(
        "Your Age (years)",
        min_value=16,
        max_value=80,
        value=30,
        help="Enter your current age in years"
    )
    
    # Health issues input
    health_issues = st.text_area(
        "Known Health Issues",
        placeholder="e.g., bad knees, back problems, heart condition, diabetes, etc.\nLeave empty if none.",
        help="List any health conditions, injuries, or physical limitations"
    )
    
    if not health_issues.strip():
        health_issues = "None reported"
    
    # Exercise time input
    exercise_time = st.selectbox(
        "Daily Exercise Time Available",
        options=[15, 30, 45, 60, 90, 120],
        index=2,  # Default to 45 minutes
        help="How many minutes per day can you dedicate to exercise?"
    )
    
    # Goal selection
    goal = st.radio(
        "Primary Goal",
        options=["Lose weight", "Gain muscle"],
        help="Select your main fitness objective"
    )
    
    # AI Provider and Model selection
    st.header("🤖 AI Configuration")
    
    # Provider selection
    provider = st.radio(
        "Choose AI Provider",
        options=["Ollama (Local)", "OpenRouter (Cloud)"],
        help="Select between local Ollama models or cloud-based OpenRouter models"
    )
    
    # Clean provider name for internal use
    provider_clean = provider.split(" ")[0]
    
    # Model selection based on provider
    if provider_clean == "Ollama":
        st.markdown("**Local Models (Ollama)**")
        model_options = [
            "gemma3:270m"  # Only working model with available system memory
        ]
        
        selected_model = st.selectbox(
            "Choose Ollama Model",
            options=model_options,
            index=0,
            help="Model optimized for your system's available memory"
        )
        
        # Ollama status
        st.info("🔧 **Ollama**: Make sure Ollama is running (`ollama serve`)")
        
    else:  # OpenRouter
        st.markdown("**Cloud Models (OpenRouter)**")
        
        # API Key input
        api_key = st.text_input(
            "OpenRouter API Key",
            type="password",
            help="Get your API key from https://openrouter.ai/keys",
            placeholder="sk-or-v1-..."
        )
        
        if api_key:
            st.session_state.openrouter_api_key = api_key
        
        # OpenRouter model selection
        openrouter_models = [
            "google/gemma-2-9b-it",
            "google/gemma-2-27b-it", 
            "anthropic/claude-3.5-sonnet",
            "openai/gpt-4o-mini",
            "meta-llama/llama-3.1-8b-instruct",
            "mistralai/mistral-7b-instruct"
        ]
        
        selected_model = st.selectbox(
            "Choose OpenRouter Model",
            options=openrouter_models,
            index=0,
            help="Powerful cloud models for better exercise recommendations"
        )
        
        # OpenRouter pricing info
        if not api_key:
            st.warning("⚠️ **API Key Required**: Enter your OpenRouter API key above")
        else:
            st.success("✅ **API Key Set**: Ready to use OpenRouter models")
        
        st.info("💰 **Note**: OpenRouter charges per token. Check pricing at openrouter.ai")

# Main content area
col1, col2 = st.columns([2, 1])

with col1:
    st.header("📋 Your Exercise Profile")
    
    # Display user profile summary
    st.info(f"""
    **Age:** {age} years  
    **Health Issues:** {health_issues}  
    **Daily Exercise Time:** {exercise_time} minutes  
    **Goal:** {goal}  
    **Provider:** {provider}  
    **Model:** {selected_model}
    """)
    
    # Generate button
    if st.button("🏥 Generate UAB Sveikata Exercise Plan", type="primary", use_container_width=True):
        with st.spinner("🤖 UAB Sveikata AI assistant is creating your personalized exercise routine..."):
            routine = generate_routine(age, health_issues, exercise_time, goal, provider_clean, selected_model)
            
            st.session_state.routine = routine
            st.session_state.routine_generated = True
    
    # Display generated routine
    if st.session_state.routine_generated and 'routine' in st.session_state:
        st.header("� Your UAB Sveikata Exercise Plan")
        st.success("✅ Your professional exercise routine has been generated by our AI health assistant!")
        
        # Display the routine in an expandable section
        with st.expander("📅 View Complete Weekly Routine", expanded=True):
            if "❌" in st.session_state.routine or "⚠️" in st.session_state.routine:
                st.error(st.session_state.routine)
            else:
                st.markdown(st.session_state.routine)
        
        # Download option
        st.download_button(
            label="📥 Download UAB Sveikata Exercise Plan",
            data=st.session_state.routine,
            file_name=f"UAB_Sveikata_exercise_plan_{age}y_{goal.lower().replace(' ', '_')}.txt",
            mime="text/plain"
        )

with col2:
    st.header("🏥 UAB Sveikata Information")
    
    st.markdown("""
    ### 🎯 How to Use UAB Sveikata AI Assistant
    1. Fill in your profile information in the sidebar
    2. Select your primary fitness goal (Lose weight or Gain muscle)
    3. Choose how much time you can dedicate daily
    4. Select AI provider (Ollama or OpenRouter)
    5. Click "Generate UAB Sveikata Exercise Plan"
    
    ### 💡 Professional Health Guidelines
    - **Personalized approach** - Each plan is tailored to your specific needs
    - **Medical safety** - Always consider your health conditions
    - **Progressive training** - Start gradually and build up intensity
    - **Consistency is key** - Regular exercise is more effective than occasional intense sessions
    
    ### ⚠️ Important Medical Disclaimer
    - **UAB Sveikata AI responses are for informational purposes only**
    - **Always consult with a healthcare provider** before starting new exercise programs
    - **Get medical clearance** if you have existing health conditions
    - **Stop exercising** if you experience pain or discomfort
    - **This AI does not replace professional medical advice**
    
    ### 🤖 About UAB Sveikata AI Assistant
    Our AI health assistant is designed to provide health and exercise recommendations only. It follows strict guidelines:
    - ✅ Only answers health and exercise questions
    - ✅ Always identifies as UAB Sveikata assistant
    - ✅ Includes medical disclaimers in all responses
    - ❌ Does not answer non-health related questions
    
    ### 🔧 Technical Features
    - **Local AI (Ollama)**: Private, secure, works offline
    - **Cloud AI (OpenRouter)**: Advanced models, requires internet
    - **Input validation**: Only accepts appropriate data formats
    - **Response validation**: Ensures medical compliance
    """)
    
    # Status indicator
    st.markdown("### 🔌 System Status")
    
    if provider_clean == "Ollama":
        col1, col2 = st.columns(2)
        
        with col1:
            if st.button("Check Ollama"):
                test_response = query_ollama("Hello", selected_model)
                if "Error:" in test_response or "❌" in test_response or "⚠️" in test_response:
                    st.error("Connection failed")
                    st.write(test_response)
                else:
                    st.success("✅ Ollama connected")
        
        with col2:
            if st.button("List Models"):
                try:
                    response = requests.get("http://localhost:11434/api/tags", timeout=5)
                    if response.status_code == 200:
                        models = response.json().get('models', [])
                        st.success(f"✅ {len(models)} models available")
                        for model in models:
                            model_name = model.get('name', 'Unknown')
                            size_gb = model.get('size', 0) / (1024**3)
                            st.write(f"📦 {model_name} ({size_gb:.1f} GB)")
                    else:
                        st.error("❌ Cannot fetch models")
                except Exception as e:
                    st.error(f"❌ Error: {str(e)}")
        
        # Memory warning for Ollama
        st.info("💡 **Tip**: If you get memory errors, try smaller models or switch to OpenRouter")
        
    else:  # OpenRouter
        if st.button("Test OpenRouter"):
            if not st.session_state.get('openrouter_api_key', ''):
                st.error("❌ Please enter your OpenRouter API key first")
            else:
                test_response = query_openrouter("Hello", selected_model)
                if "Error:" in test_response or "❌" in test_response:
                    st.error("Connection failed")
                    st.write(test_response)
                else:
                    st.success("✅ OpenRouter connected")
                    st.write(f"Response: {test_response}")
        
        st.info("🌐 **OpenRouter**: Cloud-based models, requires internet and API key")
    
    # Quick model test
    st.markdown("### 🧪 Quick Model Test")
    if st.button("Test Selected Model"):
        with st.spinner(f"Testing {selected_model}..."):
            if provider_clean == "Ollama":
                test_result = query_ollama("Say hello in one sentence.", selected_model)
            else:
                test_result = query_openrouter("Say hello in one sentence.", selected_model)
            
            if "Error:" in test_result or "❌" in test_result or "⚠️" in test_result:
                st.error("❌ Model test failed")
                st.write(test_result)
            else:
                st.success("✅ Model working!")
                st.write(f"Response: {test_result}")

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center'>
        <h4>🏥 UAB Sveikata - AI Health Assistant</h4>
        <p><strong>Professional Exercise Recommendations | Powered by AI Technology</strong></p>
        <p><small>⚠️ <strong>Medical Disclaimer:</strong> This AI assistant provides general exercise information only and does not constitute professional medical advice. Always consult qualified healthcare professionals before starting new exercise programs or making health-related decisions.</small></p>
        <p><small>📧 For medical consultations, contact UAB Sveikata directly</small></p>
    </div>
    """, 
    unsafe_allow_html=True
)