#!/usr/bin/env python3
"""
Test script to debug UAB Sveikata response validation
"""

import requests
import json

def test_ai_response():
    """Test actual AI response to see formatting"""
    
    # Test with gemma3:270m (working model)
    url = "http://localhost:11434/api/generate"
    
    prompt = """Hello, I am the "UAB Sveikata" health assistant.

Create a weekly exercise plan:
- Age: 30 years
- Health: None reported
- Time: 45 minutes/day
- Goal: Lose weight

Monday: [exercises]
Tuesday: [exercises] 
Wednesday: [exercises]
Thursday: [exercises]
Friday: [exercises]
Saturday: [exercises]
Sunday: [exercises]

This answer is generated by AI and does not constitute professional medical advice."""

    data = {
        "model": "gemma3:270m",
        "prompt": prompt,
        "stream": False
    }
    
    print("🧪 Testing AI response formatting...")
    print("=" * 60)
    
    try:
        response = requests.post(url, json=data, timeout=60)
        result = response.json()
        
        if 'error' in result:
            print(f"❌ Error: {result['error']}")
            return
        
        ai_response = result.get('response', 'No response')
        
        print(f"**Response Length:** {len(ai_response)} characters")
        print(f"**First 100 chars:** {repr(ai_response[:100])}")
        print(f"**Last 100 chars:** {repr(ai_response[-100:])}")
        
        print("\n" + "="*60)
        print("FULL RESPONSE:")
        print("="*60)
        print(ai_response)
        print("="*60)
        
        # Test validation
        print("\n🔍 Validation Tests:")
        print("-" * 30)
        
        # Check start
        expected_start = 'Hello, I am the "UAB Sveikata" health assistant.'
        starts_correctly = ai_response.startswith(expected_start)
        print(f"Starts correctly: {starts_correctly}")
        if not starts_correctly:
            print(f"Expected: {repr(expected_start)}")
            print(f"Actual start: {repr(ai_response[:len(expected_start)])}")
        
        # Check end  
        expected_end = 'This answer is generated by AI and does not constitute professional medical advice.'
        ends_correctly = ai_response.endswith(expected_end)
        print(f"Ends correctly: {ends_correctly}")
        if not ends_correctly:
            print(f"Expected: {repr(expected_end)}")
            print(f"Actual end: {repr(ai_response[-len(expected_end):])}")
            
        # Check for any whitespace issues
        clean_response = ai_response.strip()
        print(f"Response has leading/trailing whitespace: {ai_response != clean_response}")
        
        if ai_response != clean_response:
            print(f"Leading chars: {repr(ai_response[:10])}")
            print(f"Trailing chars: {repr(ai_response[-10:])}")
        
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    test_ai_response()