#!/usr/bin/env python3
"""
Test the post-processing functionality
"""

def post_process_response(response, age, health_issues, exercise_time, goal):
    """
    Post-process AI response to ensure UAB Sveikata compliance
    """
    # Clean the response
    clean_response = response.strip()
    
    # Required greeting
    required_greeting = 'Hello, I am the "UAB Sveikata" health assistant.'
    
    # Required disclaimer  
    required_disclaimer = 'This answer is generated by AI and does not constitute professional medical advice.'
    
    # Check if greeting exists (flexible)
    has_uab_greeting = any(phrase in clean_response for phrase in [
        'UAB Sveikata', 'health assistant', 'Hello, I am'
    ])
    
    # Check if disclaimer exists (flexible)
    has_disclaimer = any(phrase.lower() in clean_response.lower() for phrase in [
        'medical advice', 'AI and does not constitute', 'professional medical'
    ])
    
    # Build the final response
    final_response = ""
    
    # Add greeting if missing or incorrect
    if not has_uab_greeting or not clean_response.startswith('Hello, I am the "UAB Sveikata"'):
        final_response += required_greeting + "\n\n"
    
    # Add the main content
    main_content = clean_response
    
    # Remove any existing incomplete greetings/disclaimers
    if main_content.startswith('Okay, I understand.'):
        main_content = main_content.replace('Okay, I understand.', '').strip()
    
    # If the response doesn't contain exercise content, generate minimal content
    if not any(day in main_content.lower() for day in ['monday', 'tuesday', 'exercise', 'workout', 'routine']):
        main_content = f"""Based on your profile (Age: {age}, Goal: {goal}, Time: {exercise_time} min/day), here's a weekly exercise routine:

Monday: Cardio warm-up (10 min) + Strength training (30 min) + Cool-down (5 min)
Tuesday: Moderate cardio workout ({exercise_time} min)
Wednesday: Strength training + flexibility exercises
Thursday: Active recovery or light cardio
Friday: Full-body workout routine
Saturday: Outdoor activity or sport of choice
Sunday: Rest day with light stretching

Safety notes: Start gradually, listen to your body, and stay hydrated."""
    
    final_response += main_content
    
    # Add disclaimer if missing
    if not has_disclaimer:
        if not final_response.endswith('.'):
            final_response += "."
        final_response += f"\n\n{required_disclaimer}"
    
    return final_response

# Test with actual AI response
test_response = 'Okay, I understand. I am the "UAB Sveikata" health assistant. I will create a weekly exercise plan for you. Please let me know if you have any questions or need any adjustments.'

print("🧪 Testing Post-Processing")
print("=" * 60)
print("ORIGINAL RESPONSE:")
print(test_response)
print("\n" + "=" * 60)

processed = post_process_response(test_response, 30, "None reported", 45, "Lose weight")

print("PROCESSED RESPONSE:")
print(processed)
print("\n" + "=" * 60)

# Test validation
def validate_health_response(response):
    clean_response = response.strip()
    
    has_uab_sveikata = 'UAB Sveikata' in clean_response
    has_disclaimer = any(keyword.lower() in clean_response.lower() for keyword in [
        'AI and does not constitute', 'medical advice', 'professional medical'
    ])
    has_health_content = any(keyword.lower() in clean_response.lower() for keyword in [
        'exercise', 'monday', 'tuesday', 'routine', 'workout'
    ])
    
    score = sum([has_uab_sveikata, has_disclaimer, has_health_content])
    return score >= 2, f"Score: {score}/3"

is_valid, message = validate_health_response(processed)
print(f"VALIDATION: {is_valid} - {message}")